"use client";

import React, { useState, useMemo } from "react";
import { useRouter } from "next/navigation";
import { useExamSchedules, useArchiveExamSchedule, usePublishExamSessions, useUpdateExamSchedule, useExportExamSchedules } from "@/hooks/use-exam-schedules";
import { useRooms } from "@/hooks/use-rooms";
import { useProctors } from "@/hooks/use-users";
import { useSubjects } from "@/hooks/use-subjects";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { keepPreviousData } from "@tanstack/react-query";
import {
  Plus,
  Clock,
  FileText,
  MoreVertical,
  ChevronLeft,
  ChevronRight,
  Users,
  ShieldCheck,
  Zap,
  Building2,
  Calendar,
  Layers,
  MapPin,
  Activity,
  RotateCw,
  X,
  Send,
  Upload,
} from "lucide-react";
import { format, addDays, subDays, eachDayOfInterval, startOfWeek, parseISO, isSameDay } from "date-fns";
import { ROUTES } from "@/lib/constants/routes";
import { parseLocalDate } from "./utils";
import AutoGenerateScheduleDialog from "./components/AutoGenerateScheduleDialog";
import AutoGenerateReportDialog from "./components/AutoGenerateReportDialog";
import PublishScheduleDialog from "./components/PublishScheduleDialog";
import ImportScheduleDialog from "./components/ImportScheduleDialog";
import { CAMPUSES } from "@/lib/constants/exam";
import SearchableSelect from "@/components/ui/searchable-select";
import { useTranslations } from "next-intl";
import { getCurrentLocale } from "@/hooks/use-check-auth";
import { toast } from "sonner";

export default function ExamOfficerDashboardPage() {
  const router = useRouter();
  const t = useTranslations("Dashboard");
  const tCommon = useTranslations("Common");
  const locale = getCurrentLocale();

  const [page, setPage] = useState(1);
  const [searchParams, setSearchParams] = useState({
    subjectCode: "",
    examCode: "",
    fromDate: "",
    toDate: "",
    startTime: "",
    endTime: "",
    status: "",
    examRoomId: "",
    proctorId: "",
    campus: "",
  });
  const [showAutoGenerateDialog, setShowAutoGenerateDialog] = useState(false);
  const [showPublishDialog, setShowPublishDialog] = useState(false);
  const [showImportDialog, setShowImportDialog] = useState(false);
  const [viewMode, setViewMode] = useState<"list" | "grid">("grid");

  const { data: subjectsData } = useSubjects({ limit: 1000 });
  const { data: proctorsData } = useProctors({ limit: 1000 });
  const { data: roomsData } = useRooms({ limit: 1000 });

  // Calculate current week range for Grid View
  const currentWeekStart = searchParams.fromDate
    ? parseISO(searchParams.fromDate)
    : startOfWeek(new Date(), { weekStartsOn: 1 });

  const gridFromDate = format(currentWeekStart, "yyyy-MM-dd");
  const gridToDate = format(addDays(currentWeekStart, 6), "yyyy-MM-dd");

  const { data, isLoading, refetch, isRefetching } = useExamSchedules(
    {
      page: viewMode === 'grid' ? 1 : page,
      limit: viewMode === 'grid' ? 99999 : 10,
      ...searchParams,
      ...(viewMode === 'grid' ? { fromDate: gridFromDate, toDate: gridToDate } : {}),
    },
    { placeholderData: keepPreviousData }
  );

  const updateMutation = useUpdateExamSchedule();
  const exportMutation = useExportExamSchedules();

  const handleDragStart = (e: React.DragEvent, sessionId: string) => {
    e.dataTransfer.setData("sessionId", sessionId);
    e.dataTransfer.effectAllowed = "move";
  };

  const handleDrop = async (e: React.DragEvent, date: string, time: string, targetCampus?: string) => {
    e.preventDefault();
    const sessionId = e.dataTransfer.getData("sessionId");
    if (!sessionId) return;

    const session = schedules.find(s => s.id === sessionId);
    if (!session) return;

    try {
      // Calculate new open time using local components to avoid TZ issues
      const [year, month, day] = date.split("-").map(Number);
      const [hours, minutes] = time.split(":").map(Number);
      const newOpenTime = new Date(year, month - 1, day, hours, minutes, 0, 0);

      const payload: any = {
        examOpenTime: newOpenTime.toISOString(),
      };

      if (targetCampus) {
        payload.campus = targetCampus;
      }

      // Maintain duration if available
      if (session.examOpenTime && session.examCloseTime) {
        const originalOpen = new Date(session.examOpenTime);
        const originalClose = new Date(session.examCloseTime);
        const durationMs = originalClose.getTime() - originalOpen.getTime();
        const newCloseTime = new Date(newOpenTime.getTime() + durationMs);
        payload.examCloseTime = newCloseTime.toISOString();
      }

      await updateMutation.mutateAsync({
        id: sessionId,
        data: payload
      });
      toast.success(tCommon("success.update"));
    } catch (error: any) {
      toast.error(error?.response?.data?.message || tCommon("errors.updateFailed"));
    }
  };

  const schedules = data?.data || [];
  const totalPages = data?.meta?.totalPages || 1;

  const clearFilters = () => {
    setSearchParams({
      subjectCode: "",
      examCode: "",
      fromDate: "",
      toDate: "",
      startTime: "",
      endTime: "",
      status: "",
      examRoomId: "",
      proctorId: "",
      campus: "",
    });
    setPage(1);
  };

  const stats = {
    totalExams: data?.meta?.total || 0,
    totalStudents: schedules.reduce((acc, s) => acc + (s.studentCount || 0), 0),
    totalRooms: new Set(schedules.map(s => s.examRoomId)).size,
    campuses: new Set(schedules.map(s => s.campus)).size,
  };

  const campusThemes: Record<string, { badge: string, bg: string, border: string, text: string, shadow: string }> = {
    "HN": { badge: "bg-blue-600", bg: "bg-blue-50/30", border: "border-blue-100", text: "text-blue-700", shadow: "shadow-blue-100" },
    "HCM": { badge: "bg-orange-600", bg: "bg-orange-50/30", border: "border-orange-100", text: "text-orange-700", shadow: "shadow-orange-100" },
    "DN": { badge: "bg-emerald-600", bg: "bg-emerald-50/30", border: "border-emerald-100", text: "text-emerald-700", shadow: "shadow-emerald-100" },
    "QN": { badge: "bg-rose-600", bg: "bg-rose-50/30", border: "border-rose-100", text: "text-rose-700", shadow: "shadow-rose-100" },
    "CT": { badge: "bg-indigo-600", bg: "bg-indigo-50/30", border: "border-indigo-100", text: "text-indigo-700", shadow: "shadow-indigo-100" },
  };

  // 7 Standard Daily Exam Slots rules
  const FIXED_SLOTS = [
    { id: 1, start: "07:30", timeRange: "07:30 - 09:00" },
    { id: 2, start: "09:10", timeRange: "09:10 - 10:40" },
    { id: 3, start: "10:50", timeRange: "10:50 - 12:20" },
    { id: 4, start: "12:50", timeRange: "12:50 - 14:20" },
    { id: 5, start: "14:30", timeRange: "14:30 - 16:00" },
    { id: 6, start: "16:10", timeRange: "16:10 - 17:40" }
  ];

  const getSlotLogicForTime = (time: string) => {
    if (time === "Unknown") return "07:30"; // fallback
    const exactSlot = FIXED_SLOTS.find(slot => slot.start === time);
    if (exactSlot) return exactSlot.start;
    const [h, m] = time.split(":").map(Number);
    const totalMinutes = h * 60 + m;
    if (totalMinutes < 9 * 60 + 10) return "07:30";
    if (totalMinutes < 10 * 60 + 50) return "09:10";
    if (totalMinutes < 12 * 60 + 50) return "10:50";
    if (totalMinutes < 14 * 60 + 30) return "12:50";
    if (totalMinutes < 16 * 60 + 10) return "14:30";
    return "16:10";
  };

  const getFormattedTimeRange = (open: string | null, close: string | null) => {
    if (!open) return "N/A";
    const openDate = parseLocalDate(open);
    const closeDate = close ? parseLocalDate(close) : null;
    if (!openDate) return "N/A";
    return `${format(openDate, "HH:mm")}${closeDate ? ` - ${format(closeDate, "HH:mm")}` : ""}`;
  };

  const getHallInvigilatorDisplay = (schedule: any) =>
    schedule?.hallInvigilatorUsername || schedule?.hallInvigilatorName || t("examOfficer.schedulesPage.board.unassigned");

  const matrix = useMemo(() => schedules.reduce((acc, s) => {
    const dateStr = s.examOpenTime ? format(parseLocalDate(s.examOpenTime) || new Date(), "yyyy-MM-dd") : "Unknown";
    const rawTime = s.examOpenTime ? format(parseLocalDate(s.examOpenTime) || new Date(), "HH:mm") : "Unknown";
    const slotTime = getSlotLogicForTime(rawTime);
    const campus = s.campus || "Unknown";
    if (!acc[dateStr]) acc[dateStr] = {};
    if (!acc[dateStr][slotTime]) acc[dateStr][slotTime] = {};
    if (!acc[dateStr][slotTime][campus]) acc[dateStr][slotTime][campus] = [];
    acc[dateStr][slotTime][campus].push(s);
    return acc;
  }, {} as Record<string, Record<string, Record<string, any[]>>>), [schedules]);

  const [expandedSlot, setExpandedSlot] = useState<string | null>(null);
  const [expandedSessions, setExpandedSessions] = useState<{sessions: any[], campus: string, label: string} | null>(null);

  const gridDates = eachDayOfInterval({
    start: currentWeekStart,
    end: addDays(currentWeekStart, 6)
  }).map(d => format(d, "yyyy-MM-dd"));

  return (
    <div className="flex flex-col gap-4 p-3 md:p-4 bg-[#f0f2f5] min-h-screen">
      {/* Premium Header */}
      <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4">
        <div className="flex items-center gap-4">
          <div className="h-12 w-12 bg-gradient-to-br from-orange-500 to-orange-600 rounded-2xl flex items-center justify-center shadow-md shadow-orange-200">
            <Calendar className="h-6 w-6 text-white" />
          </div>
          <div>
            <h1 className="text-[2rem] font-black text-slate-900 tracking-tight leading-none mb-1">{t("examOfficer.examSchedules")}</h1>
            <div className="flex items-center gap-2">
              <span className="h-2 w-2 rounded-full bg-emerald-500 animate-pulse" />
              <p className="text-slate-500 text-[10px] font-black uppercase tracking-[3px]">{t("examOfficer.schedulesPage.missionControl")}</p>
            </div>
          </div>
        </div>

        <div className="flex flex-wrap items-center gap-2">
          <Button
            variant="outline"
            className="h-11 rounded-2xl border-slate-200 hover:bg-white hover:shadow-md font-bold gap-2 px-4 transition-all text-slate-600"
            onClick={() => router.push(`/${locale}${ROUTES.EXAMS_SCHEDULE_CREATE}`)}
          >
            <Plus className="h-4 w-4" /> {t("examOfficer.actions.createSchedule")}
          </Button>
          <Button
            variant="outline"
            className="h-11 rounded-2xl border-slate-200 hover:bg-white hover:shadow-md font-bold gap-2 px-4 transition-all text-blue-600 border-blue-100 bg-blue-50/30"
            onClick={() => setShowImportDialog(true)}
          >
            <Upload className="h-4 w-4" /> {t("examOfficer.actions.importSchedule")}
          </Button>
          <Button variant="outline" className="h-11 rounded-2xl border-slate-200 hover:bg-white hover:shadow-md font-bold gap-2 px-4 transition-all text-emerald-600 border-emerald-100 bg-emerald-50/30" onClick={() => setShowPublishDialog(true)}>
            <Send className="h-4 w-4" /> {t("examOfficer.actions.publishSchedule")}
          </Button>
          <Button
            variant="outline"
            disabled={isLoading || isRefetching}
            onClick={() => refetch()}
            className="h-11 rounded-2xl border-slate-200 hover:bg-white hover:shadow-md font-bold gap-2 px-4 transition-all text-orange-600 border-orange-100 bg-orange-50/30 disabled:opacity-50"
          >
            <RotateCw className={`h-4 w-4 ${isRefetching ? "animate-spin" : ""}`} />
            {tCommon("refresh")}
          </Button>
          <div className="w-[1px] h-8 bg-slate-200 mx-2 hidden lg:block" />
          <Button className="h-11 rounded-2xl bg-slate-900 text-white hover:bg-slate-800 font-bold gap-3 px-5 shadow-lg shadow-slate-200 transition-all active:scale-95" onClick={() => setShowAutoGenerateDialog(true)}>
            <Zap className="h-4 w-4 text-orange-400" /> {t("examOfficer.actions.autoCreateSchedule")}
          </Button>
          <div className="bg-white p-1.5 rounded-2xl border border-slate-200 shadow-sm flex gap-1.5 ml-2">
            <Button size="sm" variant={viewMode === "grid" ? "outline" : "ghost"} className={`rounded-xl font-black text-xs uppercase tracking-wider px-6 h-9 transition-all ${viewMode === "grid" ? "shadow-md text-orange-600 bg-orange-50/50 border-orange-200" : "text-slate-400 border-transparent"}`} onClick={() => setViewMode("grid")}>{t("examOfficer.schedulesPage.board.boardView")}</Button>
            <Button size="sm" variant={viewMode === "list" ? "outline" : "ghost"} className={`rounded-xl font-black text-xs uppercase tracking-wider px-6 h-9 transition-all ${viewMode === "list" ? "shadow-md text-orange-600 bg-orange-50/50 border-orange-200" : "text-slate-400 border-transparent"}`} onClick={() => setViewMode("list")}>{t("examOfficer.schedulesPage.board.listView")}</Button>
          </div>
        </div>
      </div>

      {/* High-Impact Stats */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        {[
          { label: t("examOfficer.schedulesPage.stats.examsThisBatch"), value: stats.totalExams, color: "text-blue-600", icon: Layers, bg: "bg-blue-100/50" },
          { label: t("examOfficer.schedulesPage.stats.totalStudents"), value: stats.totalStudents, color: "text-orange-600", icon: Users, bg: "bg-orange-100/50" },
          { label: t("examOfficer.schedulesPage.stats.availableRooms"), value: stats.totalRooms, color: "text-emerald-600", icon: MapPin, bg: "bg-emerald-100/50" },
          { label: t("examOfficer.schedulesPage.stats.activeCampuses"), value: stats.campuses, color: "text-purple-600", icon: Building2, bg: "bg-purple-100/50" },
        ].map(stat => (
          <Card key={stat.label} className="border-none shadow-sm bg-white rounded-[1.75rem] overflow-hidden group hover:shadow-lg transition-all duration-300">
            <CardContent className="p-5 flex items-center gap-4">
              <div className={`p-3 rounded-2xl ${stat.bg} group-hover:scale-110 transition-transform`}>
                <stat.icon className={`h-5 w-5 ${stat.color}`} />
              </div>
              <div>
                <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest leading-none mb-1.5">{stat.label}</p>
                <p className={`text-[1.9rem] font-black text-slate-900 leading-none`}>{stat.value.toLocaleString()}</p>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Comprehensive Filters */}
      <Card className="border-none shadow-sm bg-white rounded-[2rem] overflow-hidden">
        <CardContent className="p-6">
          <div className="flex items-center gap-4 mb-5">
            <div className="h-9 w-9 bg-slate-100 rounded-2xl flex items-center justify-center">
              <Plus className="h-4 w-4 text-slate-400 rotate-45" />
            </div>
            <div>
              <h2 className="text-lg font-black text-slate-900 tracking-tight leading-none">{t("examOfficer.schedulesPage.smartFilter.title")}</h2>
              <p className="text-[9px] font-black text-slate-400 uppercase tracking-widest mt-1">{t("examOfficer.schedulesPage.smartFilter.subtitle")}</p>
            </div>
            <div className="ml-auto flex items-center gap-4">
              <Button variant="ghost" className="text-[10px] font-black text-slate-400 hover:text-orange-600 uppercase tracking-widest" onClick={clearFilters}>{t("examOfficer.schedulesPage.smartFilter.clear")}</Button>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-5">
            <div className="space-y-2">
              <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest ml-1">{t("examOfficer.schedulesPage.filters.subject")}</label>
              <SearchableSelect
                value={searchParams.subjectCode}
                onChange={v => setSearchParams({ ...searchParams, subjectCode: v })}
                placeholder={t("examOfficer.schedulesPage.allOptions.allSubjects")}
                options={(subjectsData?.data || []).map(s => ({ value: s.code, label: s.code }))}
              />
            </div>

            <div className="space-y-2">
              <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest ml-1">{t("examOfficer.schedulesPage.filters.room")}</label>
              <SearchableSelect
                value={searchParams.examRoomId}
                onChange={v => setSearchParams({ ...searchParams, examRoomId: v })}
                placeholder={t("examOfficer.schedulesPage.allOptions.allRooms")}
                options={(roomsData?.data || []).map(r => ({ value: r.id, label: r.roomNumber }))}
              />
            </div>

            <div className="space-y-2">
              <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest ml-1">{t("examOfficer.schedulesPage.filters.proctor")}</label>
              <SearchableSelect
                value={searchParams.proctorId}
                onChange={v => setSearchParams({ ...searchParams, proctorId: v })}
                placeholder={t("examOfficer.schedulesPage.allOptions.allProctors")}
                options={(proctorsData?.data || []).map(p => ({ value: p.id, label: p.fullName || "" }))}
              />
            </div>

            <div className="space-y-2">
              <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest ml-1">{t("examOfficer.schedulesPage.filters.status")}</label>
              <SearchableSelect
                value={searchParams.status}
                onChange={v => setSearchParams({ ...searchParams, status: v })}
                placeholder={t("examOfficer.schedulesPage.allOptions.allStatuses")}
                options={[
                  { value: "Draft", label: tCommon("statuses.Draft") },
                  { value: "Scheduled", label: tCommon("statuses.Scheduled") },
                  { value: "Published", label: tCommon("statuses.Published") },
                ]}
              />
            </div>

            <div className="space-y-2">
              <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest ml-1">{t("examOfficer.schedulesPage.filters.campus")}</label>
              <SearchableSelect
                value={searchParams.campus}
                onChange={v => setSearchParams({ ...searchParams, campus: v })}
                placeholder={t("examOfficer.schedulesPage.allOptions.allCampuses")}
                options={CAMPUSES.map(c => ({ value: c, label: c }))}
              />
            </div>

            <div className="space-y-2">
              <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest ml-1">{t("examOfficer.schedulesPage.filters.fromDate")}</label>
              <div className="relative">
                <Calendar className="absolute left-4 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400" />
                <input
                  type="date"
                  className="w-full h-12 bg-slate-50 border border-slate-100 rounded-2xl pl-11 pr-4 text-xs font-bold focus:ring-2 focus:ring-orange-500/20 outline-none transition-all"
                  value={searchParams.fromDate}
                  onChange={e => setSearchParams({ ...searchParams, fromDate: e.target.value })}
                />
              </div>
            </div>

            <div className="space-y-2">
              <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest ml-1">{t("examOfficer.schedulesPage.filters.toDate")}</label>
              <div className="relative">
                <Calendar className="absolute left-4 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400" />
                <input
                  type="date"
                  className="w-full h-12 bg-slate-50 border border-slate-100 rounded-2xl pl-11 pr-4 text-xs font-bold focus:ring-2 focus:ring-orange-500/20 outline-none transition-all"
                  value={searchParams.toDate}
                  onChange={e => setSearchParams({ ...searchParams, toDate: e.target.value })}
                />
              </div>
            </div>

            <div className="space-y-2">
              <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest ml-1">{t("examOfficer.schedulesPage.filters.startTime")}</label>
              <div className="relative">
                <Clock className="absolute left-4 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400" />
                <input
                  type="time"
                  className="w-full h-12 bg-slate-50 border border-slate-100 rounded-2xl pl-11 pr-4 text-xs font-bold focus:ring-2 focus:ring-orange-500/20 outline-none transition-all"
                  value={searchParams.startTime}
                  onChange={e => setSearchParams({ ...searchParams, startTime: e.target.value })}
                />
              </div>
            </div>

            <div className="space-y-2">
              <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest ml-1">{t("examOfficer.schedulesPage.filters.endTime")}</label>
              <div className="relative">
                <Clock className="absolute left-4 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400" />
                <input
                  type="time"
                  className="w-full h-12 bg-slate-50 border border-slate-100 rounded-2xl pl-11 pr-4 text-xs font-bold focus:ring-2 focus:ring-orange-500/20 outline-none transition-all"
                  value={searchParams.endTime}
                  onChange={e => setSearchParams({ ...searchParams, endTime: e.target.value })}
                />
              </div>
            </div>

            <div className="space-y-2">
              <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest ml-1">{t("examOfficer.schedulesPage.filters.examCode")}</label>
              <div className="relative">
                <FileText className="absolute left-4 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400" />
                <input
                  type="text"
                  placeholder={t("examOfficer.schedulesPage.filters.examCodePlaceholder")}
                  className="w-full h-12 bg-slate-50 border border-slate-100 rounded-2xl pl-11 pr-4 text-xs font-bold focus:ring-2 focus:ring-orange-500/20 outline-none transition-all"
                  value={searchParams.examCode}
                  onChange={e => setSearchParams({ ...searchParams, examCode: e.target.value })}
                />
              </div>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Board Layout (Kanban Style) */}
      {isLoading ? (
        viewMode === "grid" ? (
          <div className="flex flex-col gap-6">
            {/* Day cards skeleton */}
            <div className="grid grid-cols-1 sm:grid-cols-4 lg:grid-cols-7 gap-4">
              {Array.from({ length: 7 }).map((_, i) => (
                <div key={i} className="bg-white rounded-[2rem] border border-slate-100 p-5 animate-pulse h-32">
                  <div className="h-2 w-16 bg-slate-200 rounded-full mb-3" />
                  <div className="h-8 w-12 bg-slate-200 rounded-xl mb-2" />
                  <div className="h-2 w-24 bg-slate-100 rounded-full" />
                </div>
              ))}
            </div>
            {/* Matrix skeleton */}
            <div className="bg-white border border-slate-200 rounded-[2rem] shadow-xl overflow-hidden min-h-[620px] animate-pulse p-5 flex flex-col gap-3">
              {Array.from({ length: 4 }).map((_, i) => (
                <div key={i} className="flex gap-4">
                  <div className="w-28 h-36 bg-slate-100 rounded-2xl shrink-0" />
                  {Array.from({ length: 5 }).map((_, j) => (
                    <div key={j} className="flex-1 h-36 bg-slate-50 border border-slate-100 rounded-2xl" />
                  ))}
                </div>
              ))}
            </div>
          </div>
        ) : (
          <Card className="border-none shadow-sm rounded-[2rem] overflow-hidden animate-pulse">
            <CardContent className="p-0">
              <div className="h-14 bg-slate-800 rounded-t-[2rem]" />
              {Array.from({ length: 8 }).map((_, i) => (
                <div key={i} className="flex gap-4 p-5 border-b border-slate-100">
                  <div className="h-4 w-12 bg-slate-200 rounded-full" />
                  <div className="h-4 w-24 bg-slate-200 rounded-full" />
                  <div className="h-4 w-20 bg-slate-100 rounded-full" />
                  <div className="h-4 w-16 bg-slate-100 rounded-full ml-auto" />
                </div>
              ))}
            </CardContent>
          </Card>
        )
      ) : viewMode === "grid" ? (
        <div className="flex flex-col gap-6">
          {/* Daily Quick Summary Overview */}
          <div className="grid grid-cols-1 sm:grid-cols-4 lg:grid-cols-7 gap-4">
            {gridDates.map(date => {
              const daySessionsCount = schedules.filter(s => s.examOpenTime && format(parseLocalDate(s.examOpenTime)!, "yyyy-MM-dd") === date).length;
              const isToday = isSameDay(parseISO(date), new Date());

              let theme = {
                card: "bg-white border-slate-100",
                icon: "text-slate-400 bg-slate-50",
                text: "text-slate-900",
                label: "text-slate-400",
                indicator: "bg-slate-200"
              };

              if (isToday) {
                theme = {
                  card: "bg-gradient-to-br from-orange-500 to-orange-600 border-orange-400 shadow-lg shadow-orange-100 ring-2 ring-orange-200",
                  icon: "text-white bg-white/20",
                  text: "text-white",
                  label: "text-white/70",
                  indicator: "bg-white animate-pulse"
                };
              } else if (daySessionsCount > 50) {
                theme = {
                  card: "bg-indigo-50/50 border-indigo-100 hover:border-indigo-200",
                  icon: "text-indigo-600 bg-indigo-100/50",
                  text: "text-indigo-700",
                  label: "text-indigo-400",
                  indicator: "bg-indigo-400"
                };
              } else if (daySessionsCount > 0) {
                theme = {
                  card: "bg-emerald-50/50 border-emerald-100 hover:border-emerald-200",
                  icon: "text-emerald-600 bg-emerald-100/50",
                  text: "text-emerald-700",
                  label: "text-emerald-400",
                  indicator: "bg-emerald-400"
                };
              }

              return (
                <Card key={date} className={`border-none ${theme.card} rounded-[2rem] transition-all duration-300 hover:scale-[1.02] active:scale-95 group relative overflow-hidden`}>
                  <CardContent className="p-5">
                    <div className="flex justify-between items-start mb-4">
                      <div className={`p-2.5 rounded-xl ${theme.icon} transition-colors`}>
                        <Activity className="h-4 w-4" />
                      </div>
                      <div className="flex flex-col items-end">
                        <span className={`text-[10px] font-black uppercase tracking-[2px] ${theme.label}`}>{tCommon("days." + format(parseISO(date), "EEEE").toLowerCase())}</span>
                        <span className={`text-[9px] font-bold ${theme.label} opacity-60`}>{format(parseISO(date), "dd MMM")}</span>
                      </div>
                    </div>

                    <div className="flex items-end justify-between relative z-10">
                      <div>
                        <p className={`text-3xl font-black ${theme.text} leading-none tracking-tighter`}>{daySessionsCount}</p>
                        <p className={`text-[10px] font-black uppercase tracking-widest mt-1 ${theme.label}`}>{t("examOfficer.schedules")}</p>
                      </div>
                      {daySessionsCount > 0 && (
                        <div className={`h-1.5 w-1.5 rounded-full ${theme.indicator}`} />
                      )}
                    </div>
                    <div className={`absolute -right-4 -bottom-4 h-20 w-20 rounded-full opacity-[0.03] group-hover:opacity-[0.07] transition-opacity ${isToday ? 'bg-white' : 'bg-slate-900'}`} />
                  </CardContent>
                </Card>
              );
            })}
          </div>

          {/* Weekly Navigation & Quick Filters */}
          <div className="flex items-center justify-between bg-white p-4 rounded-3xl shadow-sm border border-slate-100">
            <div className="flex items-center gap-2">
              <Button variant="outline" className="rounded-xl border-slate-200 hover:bg-slate-50 font-black text-xs h-10 px-4" onClick={() => {
                const prevWeek = subDays(currentWeekStart, 7);
                setSearchParams({ ...searchParams, fromDate: format(prevWeek, "yyyy-MM-dd") });
              }}>
                <ChevronLeft className="h-4 w-4 mr-2" /> {t("examOfficer.schedulesPage.board.prevWeek")}
              </Button>
              <div className="px-6 py-2 bg-slate-50 rounded-xl border border-slate-100 font-bold text-slate-700 h-10 flex items-center gap-3">
                <Calendar className="h-4 w-4 text-orange-600" />
                <span>{format(currentWeekStart, "dd MMM")} — {format(addDays(currentWeekStart, 6), "dd MMM, yyyy")}</span>
              </div>
              <Button variant="outline" className="rounded-xl border-slate-200 hover:bg-slate-50 font-black text-xs h-10 px-4" onClick={() => {
                const nextWeek = addDays(currentWeekStart, 7);
                setSearchParams({ ...searchParams, fromDate: format(nextWeek, "yyyy-MM-dd") });
              }}>
                {t("examOfficer.schedulesPage.board.nextWeek")} <ChevronRight className="h-4 w-4 ml-2" />
              </Button>
            </div>

            <div className="flex gap-3">
              <select className="h-10 bg-slate-50 border border-slate-200 rounded-xl px-4 text-xs font-black uppercase outline-none focus:ring-2 focus:ring-orange-500/20" value={searchParams.campus} onChange={e => setSearchParams({ ...searchParams, campus: e.target.value })}>
                <option value="">{t("examOfficer.schedulesPage.allOptions.allCampuses")}</option>
                {CAMPUSES.map(c => <option key={c} value={c}>{c}</option>)}
              </select>
              <Button variant="ghost" className="h-10 text-[10px] font-black text-slate-400 hover:text-orange-600" onClick={clearFilters}>{t("examOfficer.schedulesPage.board.reset")}</Button>
            </div>
          </div>

          {/* The Scrollable Matrix Board */}
          <div className="relative bg-white border border-slate-200 rounded-[2rem] shadow-xl overflow-hidden min-h-[620px]">
            <div className="overflow-x-auto scrollbar-thin scrollbar-thumb-slate-200 scrollbar-track-transparent">
              <div className="flex" style={{ width: 'max-content' }}>
                {/* Fixed Time Sidebar */}
                <div className="sticky left-0 z-40 bg-white/95 backdrop-blur-md border-r border-slate-200 flex flex-col pt-[72px]">
                  {FIXED_SLOTS.map(slot => (
                    <div key={slot.id} className="h-[320px] w-20 px-1.5 flex flex-col justify-center border-b border-slate-100">
                      <div className="bg-slate-50 p-3 rounded-xl border border-slate-100 text-center shadow-sm">
                        <p className="font-black text-slate-900 border-b-2 border-orange-500 pb-1 text-lg uppercase tracking-widest">
                          Slot {slot.id}
                        </p>
                        <p className="text-[10px] font-bold text-slate-500 mt-2 tracking-tighter flex items-center justify-center gap-1">
                          <Clock className="h-3 w-3 text-slate-400" /> {slot.timeRange}
                        </p>
                      </div>
                    </div>
                  ))}
                </div>

                {/* Day Columns */}
                <div className="flex flex-1">
                  {gridDates.map(date => {
                    const isToday = isSameDay(parseISO(date), new Date());
                    return (
                      <div key={date} className={`w-[320px] border-r border-slate-100 flex flex-col bg-white ${isToday ? 'bg-orange-50/10' : ''}`}>
                        {/* Day Header */}
                        <div className={`sticky top-0 z-30 p-3 border-b border-slate-100 text-center h-[64px] flex flex-col justify-center relative ${isToday ? 'bg-orange-600 text-white shadow-lg' : 'bg-slate-900 text-white shadow-md'}`}>
                          <p className="text-[10px] font-black uppercase tracking-[2px] opacity-70 mb-0.5">{tCommon("days." + format(parseISO(date), "EEEE").toLowerCase())}</p>
                          <h3 className="text-sm font-black tracking-tight">{format(parseISO(date), "dd MMM, yyyy")}</h3>
                          {isToday && <div className="absolute -bottom-1.5 left-1/2 -translate-x-1/2 bg-white text-orange-600 text-[8px] font-black px-3 py-0.5 rounded-full shadow-lg border border-orange-100 z-50">{t("examOfficer.schedulesPage.board.today")}</div>}
                        </div>

                        {/* Time Slots Area */}
                        <div className="flex flex-col">
                          {FIXED_SLOTS.map(slot => {
                            const timeData = matrix[date]?.[slot.start] || {};
                            const campusesInSlot = CAMPUSES.filter(c => timeData[c] && timeData[c].length > 0);

                            return (
                              <div
                                key={slot.id}
                                className="h-[320px] p-2 border-b border-slate-100 overflow-hidden hover:bg-slate-50/5 transition-colors flex flex-col"
                              >
                                <div
                                  className="h-full w-full p-2 overflow-y-auto scrollbar-thin scrollbar-thumb-slate-200 scrollbar-track-transparent flex flex-col gap-3"
                                  onDragOver={(e) => e.preventDefault()}
                                  onDrop={(e) => handleDrop(e, date, slot.start)}
                                >
                                  {campusesInSlot.length > 0 ? (
                                    campusesInSlot.map(campus => {
                                      const theme = campusThemes[campus] || campusThemes["HN"];
                                      const campusSessions = timeData[campus];
                                      return (
                                        <div
                                          key={campus}
                                          className={`${theme.bg} ${theme.border} border-2 rounded-2xl p-2.5 shadow-sm flex flex-col gap-2.5 transition-all duration-300 drop-shadow-sm`}
                                          onDragOver={(e) => {
                                            e.preventDefault();
                                            e.currentTarget.classList.add("ring-2", "ring-orange-500", "scale-[1.01]");
                                          }}
                                          onDragLeave={(e) => {
                                            e.currentTarget.classList.remove("ring-2", "ring-orange-500", "scale-[1.01]");
                                          }}
                                          onDrop={(e) => {
                                            e.currentTarget.classList.remove("ring-2", "ring-orange-500", "scale-[1.01]");
                                            handleDrop(e, date, slot.start, campus);
                                          }}
                                        >
                                          <div className="flex items-center justify-between border-b border-white/50 pb-2">
                                            <div className="flex items-center gap-2">
                                              <span className={`${theme.badge} text-[11px] text-white px-2.5 py-0.5 rounded-lg font-black uppercase tracking-wider shadow-sm`}>{campus}</span>
                                              <span className={`text-[11px] font-black ${theme.text} opacity-70 tracking-tight`}>{t("examOfficer.schedulesPage.campusLabel", { campus })}</span>
                                            </div>
                                            <div className="flex items-center gap-1.5 bg-white/80 px-3 py-1.5 rounded-full border border-white shadow-sm ring-4 ring-white/20">
                                              <span className={`text-sm font-black ${theme.text} leading-none`}>{campusSessions.length}</span>
                                              <span className={`text-[10px] font-black uppercase tracking-widest ${theme.text} opacity-60 leading-none`}>{t("examOfficer.schedulesPage.board.roomsSuffix")}</span>
                                            </div>
                                          </div>

                                          {/* Render max 6 cards inline, rest behind a 'more' badge */}
                                          {(() => {
                                            const MAX_INLINE = 6;
                                            const visible = campusSessions.slice(0, MAX_INLINE);
                                            const hidden = campusSessions.slice(MAX_INLINE);
                                            return (
                                              <>
                                                <div className="grid grid-cols-2 gap-1.5">
                                                  {visible.map((s: any) => (
                                                    <div
                                                      key={s.id}
                                                      draggable
                                                      onDragStart={(e) => handleDragStart(e, s.id)}
                                                      onClick={() => router.push(`/${locale}${ROUTES.EXAMS_SCHEDULE_DETAIL(s.id)}`)}
                                                      className={`group/card p-2 rounded-xl shadow-sm border transition-all cursor-pointer relative overflow-hidden flex flex-col gap-1 ${!s.proctorName ? 'bg-rose-50/30 border-rose-100 hover:border-rose-400' : 'bg-white border-slate-100 hover:border-orange-400'}`}
                                                    >
                                                      <div className="flex justify-between items-start">
                                                        <h4 className={`text-[14px] font-black uppercase truncate tracking-tight leading-none ${!s.proctorName ? 'text-rose-700' : 'text-slate-900 font-black'}`}>{s.subjectCode}</h4>
                                                        <div className="flex items-center gap-1 text-[10px] font-black text-white bg-gradient-to-r from-indigo-600 to-purple-600 px-2 py-0.5 rounded-lg leading-none shadow-sm shadow-indigo-100">
                                                          {s.examType}
                                                        </div>
                                                      </div>
                                                      <div className="flex items-center justify-between text-[11px] font-bold text-slate-500">
                                                        <div className="flex items-center gap-1.5">
                                                          <Clock className="h-3.5 w-3.5 text-slate-400" />
                                                          <span className="font-black text-slate-600">{getFormattedTimeRange(s.examOpenTime, s.examCloseTime)}</span>
                                                        </div>
                                                        <div className="flex items-center gap-1 bg-orange-100/50 text-orange-700 px-1.5 py-0.5 rounded-md">
                                                          <Users className="h-3 w-3" />
                                                          <span className="font-black tracking-tighter">{s.studentCount || 0}</span>
                                                        </div>
                                                      </div>
                                                      <div className="flex flex-col gap-1.5 mt-1">
                                                        <div className="flex items-center gap-2.5 text-xs font-black text-blue-700 bg-blue-50/50 px-2 py-1 rounded-lg border border-blue-100/50">
                                                          <MapPin className="h-3.5 w-3.5" />
                                                          <span className="truncate uppercase font-black">{s.roomNumber || t("examOfficer.schedulesPage.board.notAvailable")}</span>
                                                        </div>
                                                        <div className={`flex items-center gap-2.5 text-xs font-black px-2 py-1 rounded-lg border shadow-sm transition-colors ${s.proctorName ? 'text-slate-800 bg-slate-50 border-slate-200' : 'text-rose-700 bg-rose-50 border-rose-200'}`}>
                                                          <Users className="h-3.5 w-3.5" />
                                                          <span className="truncate uppercase font-black">{s.proctorName || t("examOfficer.schedulesPage.board.unassigned")}</span>
                                                        </div>
                                                        <div className={`flex items-center gap-2.5 text-xs font-black px-2 py-1 rounded-lg border shadow-sm transition-colors ${s.hallInvigilatorId ? 'text-slate-800 bg-emerald-50/40 border-emerald-200' : 'text-rose-700 bg-rose-50 border-rose-200'}`}>
                                                          <ShieldCheck className="h-3.5 w-3.5" />
                                                          <span className="truncate uppercase font-black">{getHallInvigilatorDisplay(s)}</span>
                                                        </div>
                                                      </div>
                                                    </div>
                                                  ))}
                                                </div>
                                                {hidden.length > 0 && (
                                                  <button
                                                    onClick={() => setExpandedSessions({ sessions: campusSessions, campus, label: `${campus} – Slot ${slot.id}` })}
                                                    className={`mt-1 w-full text-center text-[11px] font-black py-2 rounded-xl border ${theme.border} ${theme.text} bg-white/60 hover:bg-white transition-colors`}
                                                  >
                                                    {t("examOfficer.schedulesPage.board.moreRooms", { count: hidden.length })}
                                                  </button>
                                                )}
                                              </>
                                            );
                                          })()
                                          }
                                        </div>
                                      );
                                    })
                                  ) : (
                                    <div className="h-full min-h-[100px] flex flex-col items-center justify-center opacity-20 group/ready">
                                      <Plus className="h-8 w-8 text-slate-300 group-hover/ready:scale-125 transition-transform" />
                                      <span className="text-[10px] font-black text-slate-400 tracking-widest uppercase mt-2">{t("examOfficer.schedulesPage.board.ready")}</span>
                                    </div>
                                  )}
                                </div>
                              </div>
                            );
                          })}
                        </div>
                      </div>
                    );
                  })}
                </div>
              </div>
            </div>
          </div>
        </div>
      ) : (
        /* List View remains existing clean version */
        <Card className="border-none shadow-xl rounded-3xl overflow-hidden bg-white">
          <div className="overflow-x-auto">
            <table className="w-full text-sm text-left">
              <thead className="bg-[#1e293b] text-white text-[10px] font-black uppercase tracking-widest">
                <tr>
                  <th className="p-6">{t("examOfficer.table.campus")}</th>
                  <th className="p-6">{t("examOfficer.table.subject")}</th>
                  <th className="p-6">{t("examOfficer.table.date")}</th>
                  <th className="p-6 text-center">{t("examOfficer.table.time")}</th>
                  <th className="p-6">{t("examOfficer.table.type")}</th>
                  <th className="p-6">{t("examOfficer.table.room")}</th>
                  <th className="p-6">{t("examOfficer.schedulesPage.board.studentSuffix")}</th>
                  <th className="p-6">{t("examOfficer.table.status")}</th>
                  <th className="p-6 text-right pr-10">{tCommon("actions")}</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {isLoading ? (
                  <tr><td colSpan={10} className="p-24 text-center text-slate-400 font-bold italic">{tCommon("loading")}</td></tr>
                ) : schedules.length === 0 ? (
                  <tr><td colSpan={10} className="p-24 text-center text-slate-400 font-bold italic">{tCommon("noResults")}</td></tr>
                ) : schedules.map(s => (
                  <tr key={s.id} className="hover:bg-slate-50 transition-colors cursor-pointer group" onClick={() => router.push(`/${locale}${ROUTES.EXAMS_SCHEDULE_DETAIL(s.id)}`)}>
                    <td className="p-5 px-6"><span className={`${campusThemes[s.campus || "HN"].badge} text-white px-3 py-1 rounded-xl text-[10px] font-black shadow-sm`}>{s.campus}</span></td>
                    <td className="p-5 font-black text-slate-800 group-hover:text-orange-600 transition-colors text-base uppercase">{s.subjectCode}</td>
                    <td className="p-5 font-bold text-slate-500">{s.examOpenTime ? format(parseLocalDate(s.examOpenTime)!, "dd/MM/yyyy") : "-"}</td>
                    <td className="p-5 text-center"><div className="flex items-center justify-center gap-1.5 font-black text-slate-700 italic"><Clock className="h-4 w-4 text-orange-500" />{s.examOpenTime ? format(parseLocalDate(s.examOpenTime)!, "HH:mm") : "-"}</div></td>
                    <td className="p-5 text-[10px] font-bold text-slate-400 uppercase tracking-widest">{s.examType}</td>
                    <td className="p-5 font-black text-slate-700">{s.roomNumber}</td>
                    <td className="p-5 font-black text-orange-600">{s.studentCount || 0}</td>
                    <td className="p-5"><span className={`text-[10px] font-black px-4 py-1.5 rounded-full border shadow-sm ${s.status === 'Draft' ? 'bg-orange-50 text-orange-600 border-orange-100' : 'bg-green-50 text-green-600 border-green-100'}`}>{tCommon(`statuses.${s.status}`)}</span></td>
                    <td className="p-5 text-right pr-10"><Button variant="ghost" size="sm" className="h-10 w-10 p-0 rounded-2xl hover:bg-white hover:shadow-lg"><MoreVertical className="h-5 w-5 text-slate-300" /></Button></td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <div className="p-6 border-t border-slate-100 bg-slate-50/30 flex items-center justify-between">
            <div className="text-xs font-black text-slate-400 tracking-widest italic uppercase">{tCommon("showing")} {schedules.length} {t("examOfficer.schedules")} / {tCommon("page")} {page}</div>
            <div className="flex gap-3">
              <Button size="sm" variant="outline" className="h-10 px-6 rounded-2xl font-black bg-white shadow-sm border-slate-200" onClick={() => setPage(p => p - 1)} disabled={page === 1}>{tCommon("previous")}</Button>
              <Button size="sm" variant="outline" className="h-10 px-6 rounded-2xl font-black bg-white shadow-sm border-slate-200" onClick={() => setPage(p => p + 1)} disabled={page === totalPages}>{tCommon("next")}</Button>
            </div>
          </div>
        </Card>
      )}

      {/* Legend Footer */}
      <div className="flex flex-wrap gap-8 items-center justify-center bg-white p-6 rounded-[2.5rem] border border-slate-100 shadow-xl mt-4">
        {Object.entries(campusThemes).map(([campus, theme]) => (
          <div key={campus} className="flex items-center gap-3">
            <div className={`w-4 h-4 rounded-xl ${theme.badge} shadow-lg ${theme.shadow}`} />
            <span className="text-xs font-black text-slate-500 uppercase tracking-widest">{t("examOfficer.schedulesPage.campusLabel", { campus })}</span>
            <div className="h-1.5 w-12 bg-slate-100 rounded-full ml-1" />
          </div>
        ))}
      </div>

      <AutoGenerateScheduleDialog isOpen={showAutoGenerateDialog} onClose={() => setShowAutoGenerateDialog(false)} />
      <AutoGenerateReportDialog />
      <PublishScheduleDialog isOpen={showPublishDialog} onClose={() => setShowPublishDialog(false)} />
      <ImportScheduleDialog isOpen={showImportDialog} onClose={() => setShowImportDialog(false)} />

      {/* "Show More" Sessions Panel */}
      {expandedSessions && (
        <div className="fixed inset-0 z-[9998] flex justify-end">
          <div className="absolute inset-0 bg-slate-900/30 backdrop-blur-sm" onClick={() => setExpandedSessions(null)} />
          <div className="relative w-[480px] h-full bg-white shadow-2xl flex flex-col animate-in slide-in-from-right duration-300">
            <div className="p-5 bg-slate-900 text-white flex items-center justify-between shrink-0">
              <div>
                <p className="text-[10px] font-black uppercase tracking-widest text-white/50 mb-1">{t("examOfficer.schedulesPage.board.allRooms")}</p>
                <h3 className="text-lg font-black">{expandedSessions.label}</h3>
                <p className="text-xs text-white/60 font-bold mt-0.5">{t("examOfficer.schedulesPage.board.sessionsTotal", { count: expandedSessions.sessions.length })}</p>
              </div>
              <Button variant="ghost" size="sm" className="text-white/70 hover:text-white hover:bg-white/10 rounded-xl h-9 w-9 p-0" onClick={() => setExpandedSessions(null)}>
                <X className="h-5 w-5" />
              </Button>
            </div>
            <div className="flex-1 overflow-y-auto p-4 flex flex-col gap-2 bg-slate-50">
              {expandedSessions.sessions.map((s: any) => (
                <div
                  key={s.id}
                  onClick={() => { router.push(`/${locale}${ROUTES.EXAMS_SCHEDULE_DETAIL(s.id)}`); setExpandedSessions(null); }}
                  className={`bg-white rounded-2xl border p-4 shadow-sm cursor-pointer hover:shadow-md transition-all flex flex-col gap-2 ${!s.proctorName ? 'border-rose-200' : 'border-slate-100'}`}
                >
                  <div className="flex justify-between items-start">
                    <span className={`text-base font-black uppercase ${!s.proctorName ? 'text-rose-700' : 'text-slate-900'}`}>{s.subjectCode}</span>
                    <span className="text-[10px] font-black text-white bg-gradient-to-r from-indigo-600 to-purple-600 px-2.5 py-1 rounded-lg">{s.examType}</span>
                  </div>
                  <div className="flex flex-wrap gap-3 text-xs font-bold text-slate-500">
                    <span className="flex items-center gap-1.5 text-blue-700 bg-blue-50 px-2 py-1 rounded-lg border border-blue-100"><MapPin className="h-3 w-3" /> {s.roomNumber || t("examOfficer.schedulesPage.board.notAvailable")}</span>
                    <span className="flex items-center gap-1.5 bg-orange-50 text-orange-700 px-2 py-1 rounded-lg border border-orange-100"><Clock className="h-3 w-3" /> {getFormattedTimeRange(s.examOpenTime, s.examCloseTime)}</span>
                    <span className="flex items-center gap-1.5 bg-orange-50 text-orange-700 px-2 py-1 rounded-lg border border-orange-100"><Users className="h-3 w-3" /> {s.studentCount || 0}</span>
                    <span className={`flex items-center gap-1.5 px-2 py-1 rounded-lg border ${s.proctorName ? 'text-slate-700 bg-slate-50 border-slate-200' : 'text-rose-700 bg-rose-50 border-rose-200'}`}><Users className="h-3 w-3" /> {s.proctorName || t("examOfficer.schedulesPage.board.unassigned")}</span>
                    <span className={`flex items-center gap-1.5 px-2 py-1 rounded-lg border ${s.hallInvigilatorId ? 'text-slate-700 bg-emerald-50 border-emerald-200' : 'text-rose-700 bg-rose-50 border-rose-200'}`}><ShieldCheck className="h-3 w-3" /> {getHallInvigilatorDisplay(s)}</span>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
