"use client";

import React, { useState } from "react";
import { useRouter } from "next/navigation";
import { useExamSchedules, useArchiveExamSchedule, usePublishExamSessions, useUpdateExamSchedule } from "@/hooks/use-exam-schedules";
import { useRooms } from "@/hooks/use-rooms";
import { useProctors } from "@/hooks/use-users";
import { useSubjects } from "@/hooks/use-subjects";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import {
  Plus,
  Clock,
  FileText,
  MoreVertical,
  ChevronLeft,
  ChevronRight,
  Upload,
  Users,
  Zap,
  Download,
  Building2,
  Calendar,
  Layers,
  MapPin,
  Activity,
} from "lucide-react";
import { format, addDays, subDays, eachDayOfInterval, startOfWeek, parseISO, isSameDay } from "date-fns";
import { ROUTES } from "@/lib/constants/routes";
import { parseLocalDate } from "./utils";
import ImportScheduleDialog from "./components/ImportScheduleDialog";
import ImportProctorDialog from "./components/ImportProctorDialog";
import ImportExamCodeDialog from "./components/ImportExamCodeDialog";
import AutoGenerateScheduleDialog from "./components/AutoGenerateScheduleDialog";
import { CAMPUSES } from "@/lib/constants/exam";
import { useTranslations } from "next-intl";
import { getCurrentLocale } from "@/hooks/use-check-auth";
import { examSchedulesApi } from "@/lib/api/exam-schedules";
import { toast } from "sonner";

export default function ExamOfficerDashboardPage() {
  const router = useRouter();
  const t = useTranslations("Dashboard");
  const tCommon = useTranslations("Common");
  const locale = getCurrentLocale();

  const [page, setPage] = useState(1);
  const [searchParams, setSearchParams] = useState({
    subjectCode: "",
    examCode: "",
    fromDate: "",
    toDate: "",
    startTime: "",
    endTime: "",
    status: "",
    examRoomId: "",
    proctorId: "",
    campus: "",
  });
  const [showScheduleDialog, setShowScheduleDialog] = useState(false);
  const [showProctorDialog, setShowProctorDialog] = useState(false);
  const [showExamCodeDialog, setShowExamCodeDialog] = useState(false);
  const [showAutoGenerateDialog, setShowAutoGenerateDialog] = useState(false);
  const [viewMode, setViewMode] = useState<"list" | "grid">("grid");

  const { data: subjectsData } = useSubjects({ limit: 1000 });
  const { data: proctorsData } = useProctors({ limit: 1000 });
  const { data: roomsData } = useRooms({ limit: 1000 });

  // Calculate current week range for Grid View
  const currentWeekStart = searchParams.fromDate
    ? parseISO(searchParams.fromDate)
    : startOfWeek(new Date(), { weekStartsOn: 1 });

  const gridFromDate = format(currentWeekStart, "yyyy-MM-dd");
  const gridToDate = format(addDays(currentWeekStart, 6), "yyyy-MM-dd");

  const { data, isLoading } = useExamSchedules({
    page: viewMode === 'grid' ? 1 : page,
    limit: viewMode === 'grid' ? 2000 : 10,
    ...searchParams,
    ...(viewMode === 'grid' ? { fromDate: gridFromDate, toDate: gridToDate } : {}),
  });

  const updateMutation = useUpdateExamSchedule();

  const handleDragStart = (e: React.DragEvent, sessionId: string) => {
    e.dataTransfer.setData("sessionId", sessionId);
    e.dataTransfer.effectAllowed = "move";
  };

  const handleDrop = async (e: React.DragEvent, date: string, time: string, targetCampus?: string) => {
    e.preventDefault();
    const sessionId = e.dataTransfer.getData("sessionId");
    if (!sessionId) return;

    const session = schedules.find(s => s.id === sessionId);
    if (!session) return;

    try {
      // Calculate new open time using local components to avoid TZ issues
      const [year, month, day] = date.split("-").map(Number);
      const [hours, minutes] = time.split(":").map(Number);
      const newOpenTime = new Date(year, month - 1, day, hours, minutes, 0, 0);

      const payload: any = {
        examOpenTime: newOpenTime.toISOString(),
      };

      if (targetCampus) {
        payload.campus = targetCampus;
      }

      // Maintain duration if available
      if (session.examOpenTime && session.examCloseTime) {
        const originalOpen = new Date(session.examOpenTime);
        const originalClose = new Date(session.examCloseTime);
        const durationMs = originalClose.getTime() - originalOpen.getTime();
        const newCloseTime = new Date(newOpenTime.getTime() + durationMs);
        payload.examCloseTime = newCloseTime.toISOString();
      }

      await updateMutation.mutateAsync({
        id: sessionId,
        data: payload
      });
      toast.success(tCommon("success.update"));
    } catch (error: any) {
      toast.error(error?.response?.data?.message || tCommon("errors.updateFailed"));
    }
  };

  const schedules = data?.data || [];
  const totalPages = data?.meta?.totalPages || 1;

  const clearFilters = () => {
    setSearchParams({
      subjectCode: "",
      examCode: "",
      fromDate: "",
      toDate: "",
      startTime: "",
      endTime: "",
      status: "",
      examRoomId: "",
      proctorId: "",
      campus: "",
    });
    setPage(1);
  };

  const handleExport = async () => {
    try {
      const blob = await examSchedulesApi.export(searchParams);
      const url = window.URL.createObjectURL(new Blob([blob]));
      const link = document.createElement("a");
      link.href = url;
      link.setAttribute("download", `StudentReport_${format(new Date(), "dd-MM-yyyy")}.xlsx`);
      document.body.appendChild(link);
      link.click();
      link.parentNode?.removeChild(link);
      toast.success("Exported");
    } catch (err) {
      toast.error("Export failed");
    }
  };

  const stats = {
    totalExams: data?.meta?.total || 0,
    totalStudents: schedules.reduce((acc, s) => acc + (s.studentCount || 0), 0),
    totalRooms: new Set(schedules.map(s => s.examRoomId)).size,
    campuses: new Set(schedules.map(s => s.campus)).size,
  };

  const campusThemes: Record<string, { badge: string, bg: string, border: string, text: string, shadow: string }> = {
    "HN": { badge: "bg-blue-600", bg: "bg-blue-50/30", border: "border-blue-100", text: "text-blue-700", shadow: "shadow-blue-100" },
    "HCM": { badge: "bg-orange-600", bg: "bg-orange-50/30", border: "border-orange-100", text: "text-orange-700", shadow: "shadow-orange-100" },
    "DN": { badge: "bg-emerald-600", bg: "bg-emerald-50/30", border: "border-emerald-100", text: "text-emerald-700", shadow: "shadow-emerald-100" },
    "QN": { badge: "bg-rose-600", bg: "bg-rose-50/30", border: "border-rose-100", text: "text-rose-700", shadow: "shadow-rose-100" },
    "CT": { badge: "bg-indigo-600", bg: "bg-indigo-50/30", border: "border-indigo-100", text: "text-indigo-700", shadow: "shadow-indigo-100" },
  };

  // Dynamic time slots based on data + Standard Default Slots
  const DEFAULT_TIME_SLOTS = ["07:30", "09:30", "13:30", "15:30"];
  const dynamicTimeSlots = Array.from(new Set(schedules.map(s =>
    s.examOpenTime ? format(parseLocalDate(s.examOpenTime) || new Date(), "HH:mm") : null
  ).filter(Boolean)));

  const timeSlots = Array.from(new Set([...DEFAULT_TIME_SLOTS, ...dynamicTimeSlots]))
    .sort((a, b) => a!.localeCompare(b!));

  const getFormattedTimeRange = (open: string | null, close: string | null) => {
    if (!open) return "N/A";
    const openDate = parseLocalDate(open);
    const closeDate = close ? parseLocalDate(close) : null;
    if (!openDate) return "N/A";
    return `${format(openDate, "HH:mm")}${closeDate ? ` - ${format(closeDate, "HH:mm")}` : ""}`;
  };

  const matrix = schedules.reduce((acc, s) => {
    const dateStr = s.examOpenTime ? format(parseLocalDate(s.examOpenTime) || new Date(), "yyyy-MM-dd") : "Unknown";
    const startTime = s.examOpenTime ? format(parseLocalDate(s.examOpenTime) || new Date(), "HH:mm") : "Unknown";
    const campus = s.campus || "Unknown";
    if (!acc[dateStr]) acc[dateStr] = {};
    if (!acc[dateStr][startTime]) acc[dateStr][startTime] = {};
    if (!acc[dateStr][startTime][campus]) acc[dateStr][startTime][campus] = [];
    acc[dateStr][startTime][campus].push(s);
    return acc;
  }, {} as Record<string, Record<string, Record<string, any[]>>>);

  const gridDates = eachDayOfInterval({
    start: currentWeekStart,
    end: addDays(currentWeekStart, 6)
  }).map(d => format(d, "yyyy-MM-dd"));

  return (
    <div className="flex flex-col gap-6 p-4 md:p-6 bg-[#f0f2f5] min-h-screen">
      {/* Premium Header */}
      <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-6">
        <div className="flex items-center gap-5">
          <div className="h-14 w-14 bg-gradient-to-br from-orange-500 to-orange-600 rounded-3xl flex items-center justify-center shadow-lg shadow-orange-200">
            <Calendar className="h-7 w-7 text-white" />
          </div>
          <div>
            <h1 className="text-3xl font-black text-slate-900 tracking-tight leading-none mb-1">{t("examOfficer.examSchedules")}</h1>
            <div className="flex items-center gap-2">
              <span className="h-2 w-2 rounded-full bg-emerald-500 animate-pulse" />
              <p className="text-slate-500 text-[10px] font-black uppercase tracking-[3px]">{t("examOfficer.schedulesPage.missionControl")}</p>
            </div>
          </div>
        </div>

        <div className="flex flex-wrap items-center gap-3">
          <Button variant="outline" className="h-12 rounded-2xl border-slate-200 hover:bg-white hover:shadow-lg font-bold gap-2 px-5 transition-all text-slate-600" onClick={() => setShowScheduleDialog(true)}>
            <Upload className="h-4 w-4" /> {t("examOfficer.actions.importSchedule")}
          </Button>
          <Button variant="outline" className="h-12 rounded-2xl border-slate-200 hover:bg-white hover:shadow-lg font-bold gap-2 px-5 transition-all text-slate-600" onClick={() => setShowProctorDialog(true)}>
            <Users className="h-4 w-4" /> {t("examOfficer.actions.importProctors")}
          </Button>
          <Button variant="outline" className="h-12 rounded-2xl border-slate-200 hover:bg-white hover:shadow-lg font-bold gap-2 px-5 transition-all text-slate-600" onClick={() => setShowExamCodeDialog(true)}>
            <FileText className="h-4 w-4" /> {t("examOfficer.actions.importExamCodes")}
          </Button>
          <Button variant="outline" className="h-12 rounded-2xl border-slate-200 hover:bg-white hover:shadow-lg font-bold gap-2 px-5 transition-all text-orange-600 border-orange-100 bg-orange-50/30" onClick={handleExport}>
            <Download className="h-4 w-4" /> {t("examOfficer.actions.export")}
          </Button>
          <div className="w-[1px] h-8 bg-slate-200 mx-2 hidden lg:block" />
          <Button className="h-12 rounded-2xl bg-slate-900 text-white hover:bg-slate-800 font-bold gap-3 px-6 shadow-xl shadow-slate-200 transition-all active:scale-95" onClick={() => setShowAutoGenerateDialog(true)}>
            <Zap className="h-4 w-4 text-orange-400" /> {t("examOfficer.actions.autoCreateSchedule")}
          </Button>
          <div className="bg-white p-1.5 rounded-2xl border border-slate-200 shadow-sm flex gap-1.5 ml-2">
            <Button size="sm" variant={viewMode === "grid" ? "outline" : "ghost"} className={`rounded-xl font-black text-xs uppercase tracking-wider px-6 h-9 transition-all ${viewMode === "grid" ? "shadow-md text-orange-600 bg-orange-50/50 border-orange-200" : "text-slate-400 border-transparent"}`} onClick={() => setViewMode("grid")}>{t("examOfficer.schedulesPage.board.boardView")}</Button>
            <Button size="sm" variant={viewMode === "list" ? "outline" : "ghost"} className={`rounded-xl font-black text-xs uppercase tracking-wider px-6 h-9 transition-all ${viewMode === "list" ? "shadow-md text-orange-600 bg-orange-50/50 border-orange-200" : "text-slate-400 border-transparent"}`} onClick={() => setViewMode("list")}>{t("examOfficer.schedulesPage.board.listView")}</Button>
          </div>
        </div>
      </div>

      {/* High-Impact Stats */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-5">
        {[
          { label: t("examOfficer.schedulesPage.stats.examsThisBatch"), value: stats.totalExams, color: "text-blue-600", icon: Layers, bg: "bg-blue-100/50" },
          { label: t("examOfficer.schedulesPage.stats.totalStudents"), value: stats.totalStudents, color: "text-orange-600", icon: Users, bg: "bg-orange-100/50" },
          { label: t("examOfficer.schedulesPage.stats.availableRooms"), value: stats.totalRooms, color: "text-emerald-600", icon: MapPin, bg: "bg-emerald-100/50" },
          { label: t("examOfficer.schedulesPage.stats.activeCampuses"), value: stats.campuses, color: "text-purple-600", icon: Building2, bg: "bg-purple-100/50" },
        ].map(stat => (
          <Card key={stat.label} className="border-none shadow-sm bg-white rounded-3xl overflow-hidden group hover:shadow-xl transition-all duration-300">
            <CardContent className="p-6 flex items-center gap-5">
              <div className={`p-4 rounded-2xl ${stat.bg} group-hover:scale-110 transition-transform`}>
                <stat.icon className={`h-6 w-6 ${stat.color}`} />
              </div>
              <div>
                <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest leading-none mb-1.5">{stat.label}</p>
                <p className={`text-2xl font-black text-slate-900`}>{stat.value.toLocaleString()}</p>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Comprehensive Filters */}
      <Card className="border-none shadow-sm bg-white rounded-[2.5rem] overflow-hidden">
        <CardContent className="p-8">
          <div className="flex items-center gap-4 mb-6">
            <div className="h-10 w-10 bg-slate-100 rounded-2xl flex items-center justify-center">
              <Plus className="h-5 w-5 text-slate-400 rotate-45" />
            </div>
            <div>
              <h2 className="text-xl font-black text-slate-900 tracking-tight leading-none">{t("examOfficer.schedulesPage.smartFilter.title")}</h2>
              <p className="text-[9px] font-black text-slate-400 uppercase tracking-widest mt-1">{t("examOfficer.schedulesPage.smartFilter.subtitle")}</p>
            </div>
            <div className="ml-auto flex items-center gap-4">
              <Button variant="ghost" className="text-[10px] font-black text-slate-400 hover:text-orange-600 uppercase tracking-widest" onClick={clearFilters}>{t("examOfficer.schedulesPage.smartFilter.clear")}</Button>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-6">
            <div className="space-y-2">
              <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest ml-1">{t("examOfficer.schedulesPage.filters.subject")}</label>
              <select
                className="w-full h-12 bg-slate-50 border border-slate-100 rounded-2xl px-4 text-xs font-bold focus:ring-2 focus:ring-orange-500/20 outline-none transition-all"
                value={searchParams.subjectCode}
                onChange={e => setSearchParams({ ...searchParams, subjectCode: e.target.value })}
              >
                <option value="">{t("examOfficer.schedulesPage.allOptions.allSubjects")}</option>
                {subjectsData?.data?.map(s => <option key={s.id} value={s.code}>{s.code} — {s.name}</option>)}
              </select>
            </div>

            <div className="space-y-2">
              <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest ml-1">{t("examOfficer.schedulesPage.filters.room")}</label>
              <select
                className="w-full h-12 bg-slate-50 border border-slate-100 rounded-2xl px-4 text-xs font-bold focus:ring-2 focus:ring-orange-500/20 outline-none transition-all"
                value={searchParams.examRoomId}
                onChange={e => setSearchParams({ ...searchParams, examRoomId: e.target.value })}
              >
                <option value="">{t("examOfficer.schedulesPage.allOptions.allRooms")}</option>
                {roomsData?.data?.map(r => <option key={r.id} value={r.id}>{r.roomNumber}</option>)}
              </select>
            </div>

            <div className="space-y-2">
              <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest ml-1">{t("examOfficer.schedulesPage.filters.proctor")}</label>
              <select
                className="w-full h-12 bg-slate-50 border border-slate-100 rounded-2xl px-4 text-xs font-bold focus:ring-2 focus:ring-orange-500/20 outline-none transition-all"
                value={searchParams.proctorId}
                onChange={e => setSearchParams({ ...searchParams, proctorId: e.target.value })}
              >
                <option value="">{t("examOfficer.schedulesPage.allOptions.allProctors")}</option>
                {proctorsData?.data?.map(p => <option key={p.id} value={p.id}>{p.fullName}</option>)}
              </select>
            </div>

            <div className="space-y-2">
              <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest ml-1">{t("examOfficer.schedulesPage.filters.status")}</label>
              <select
                className="w-full h-12 bg-slate-50 border border-slate-100 rounded-2xl px-4 text-xs font-bold focus:ring-2 focus:ring-orange-500/20 outline-none transition-all"
                value={searchParams.status}
                onChange={e => setSearchParams({ ...searchParams, status: e.target.value })}
              >
                <option value="">{t("examOfficer.schedulesPage.allOptions.allStatuses")}</option>
                <option value="Draft">{tCommon("statuses.Draft")}</option>
                <option value="Scheduled">{tCommon("statuses.Scheduled")}</option>
                <option value="Published">{tCommon("statuses.Published")}</option>
              </select>
            </div>

            <div className="space-y-2">
              <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest ml-1">{t("examOfficer.schedulesPage.filters.campus")}</label>
              <select
                className="w-full h-12 bg-slate-50 border border-slate-100 rounded-2xl px-4 text-xs font-bold focus:ring-2 focus:ring-orange-500/20 outline-none transition-all"
                value={searchParams.campus}
                onChange={e => setSearchParams({ ...searchParams, campus: e.target.value })}
              >
                <option value="">{t("examOfficer.schedulesPage.allOptions.allCampuses")}</option>
                {CAMPUSES.map(c => <option key={c} value={c}>{c}</option>)}
              </select>
            </div>

            <div className="space-y-2">
              <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest ml-1">{t("examOfficer.schedulesPage.filters.fromDate")}</label>
              <div className="relative">
                <Calendar className="absolute left-4 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400" />
                <input
                  type="date"
                  className="w-full h-12 bg-slate-50 border border-slate-100 rounded-2xl pl-11 pr-4 text-xs font-bold focus:ring-2 focus:ring-orange-500/20 outline-none transition-all"
                  value={searchParams.fromDate}
                  onChange={e => setSearchParams({ ...searchParams, fromDate: e.target.value })}
                />
              </div>
            </div>

            <div className="space-y-2">
              <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest ml-1">{t("examOfficer.schedulesPage.filters.toDate")}</label>
              <div className="relative">
                <Calendar className="absolute left-4 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400" />
                <input
                  type="date"
                  className="w-full h-12 bg-slate-50 border border-slate-100 rounded-2xl pl-11 pr-4 text-xs font-bold focus:ring-2 focus:ring-orange-500/20 outline-none transition-all"
                  value={searchParams.toDate}
                  onChange={e => setSearchParams({ ...searchParams, toDate: e.target.value })}
                />
              </div>
            </div>

            <div className="space-y-2">
              <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest ml-1">{t("examOfficer.schedulesPage.filters.startTime")}</label>
              <div className="relative">
                <Clock className="absolute left-4 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400" />
                <input
                  type="time"
                  className="w-full h-12 bg-slate-50 border border-slate-100 rounded-2xl pl-11 pr-4 text-xs font-bold focus:ring-2 focus:ring-orange-500/20 outline-none transition-all"
                  value={searchParams.startTime}
                  onChange={e => setSearchParams({ ...searchParams, startTime: e.target.value })}
                />
              </div>
            </div>

            <div className="space-y-2">
              <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest ml-1">{t("examOfficer.schedulesPage.filters.endTime")}</label>
              <div className="relative">
                <Clock className="absolute left-4 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400" />
                <input
                  type="time"
                  className="w-full h-12 bg-slate-50 border border-slate-100 rounded-2xl pl-11 pr-4 text-xs font-bold focus:ring-2 focus:ring-orange-500/20 outline-none transition-all"
                  value={searchParams.endTime}
                  onChange={e => setSearchParams({ ...searchParams, endTime: e.target.value })}
                />
              </div>
            </div>

            <div className="space-y-2">
              <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest ml-1">{t("examOfficer.schedulesPage.filters.examCode")}</label>
              <div className="relative">
                <FileText className="absolute left-4 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400" />
                <input
                  type="text"
                  placeholder={t("examOfficer.schedulesPage.filters.examCodePlaceholder")}
                  className="w-full h-12 bg-slate-50 border border-slate-100 rounded-2xl pl-11 pr-4 text-xs font-bold focus:ring-2 focus:ring-orange-500/20 outline-none transition-all"
                  value={searchParams.examCode}
                  onChange={e => setSearchParams({ ...searchParams, examCode: e.target.value })}
                />
              </div>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Board Layout (Kanban Style) */}
      {viewMode === "grid" ? (
        <div className="flex flex-col gap-6">
          {/* Daily Quick Summary Overview */}
          <div className="grid grid-cols-1 sm:grid-cols-4 lg:grid-cols-7 gap-4">
            {gridDates.map(date => {
              const daySessionsCount = schedules.filter(s => s.examOpenTime && format(parseLocalDate(s.examOpenTime)!, "yyyy-MM-dd") === date).length;
              const isToday = isSameDay(parseISO(date), new Date());

              let theme = {
                card: "bg-white border-slate-100",
                icon: "text-slate-400 bg-slate-50",
                text: "text-slate-900",
                label: "text-slate-400",
                indicator: "bg-slate-200"
              };

              if (isToday) {
                theme = {
                  card: "bg-gradient-to-br from-orange-500 to-orange-600 border-orange-400 shadow-lg shadow-orange-100 ring-2 ring-orange-200",
                  icon: "text-white bg-white/20",
                  text: "text-white",
                  label: "text-white/70",
                  indicator: "bg-white animate-pulse"
                };
              } else if (daySessionsCount > 50) {
                theme = {
                  card: "bg-indigo-50/50 border-indigo-100 hover:border-indigo-200",
                  icon: "text-indigo-600 bg-indigo-100/50",
                  text: "text-indigo-700",
                  label: "text-indigo-400",
                  indicator: "bg-indigo-400"
                };
              } else if (daySessionsCount > 0) {
                theme = {
                  card: "bg-emerald-50/50 border-emerald-100 hover:border-emerald-200",
                  icon: "text-emerald-600 bg-emerald-100/50",
                  text: "text-emerald-700",
                  label: "text-emerald-400",
                  indicator: "bg-emerald-400"
                };
              }

              return (
                <Card key={date} className={`border-none ${theme.card} rounded-[2rem] transition-all duration-300 hover:scale-[1.02] active:scale-95 group relative overflow-hidden`}>
                  <CardContent className="p-5">
                    <div className="flex justify-between items-start mb-4">
                      <div className={`p-2.5 rounded-xl ${theme.icon} transition-colors`}>
                        <Activity className="h-4 w-4" />
                      </div>
                      <div className="flex flex-col items-end">
                        <span className={`text-[10px] font-black uppercase tracking-[2px] ${theme.label}`}>{tCommon("days." + format(parseISO(date), "EEEE").toLowerCase())}</span>
                        <span className={`text-[9px] font-bold ${theme.label} opacity-60`}>{format(parseISO(date), "dd MMM")}</span>
                      </div>
                    </div>

                    <div className="flex items-end justify-between relative z-10">
                      <div>
                        <p className={`text-3xl font-black ${theme.text} leading-none tracking-tighter`}>{daySessionsCount}</p>
                        <p className={`text-[10px] font-black uppercase tracking-widest mt-1 ${theme.label}`}>{t("examOfficer.schedules")}</p>
                      </div>
                      {daySessionsCount > 0 && (
                        <div className={`h-1.5 w-1.5 rounded-full ${theme.indicator}`} />
                      )}
                    </div>
                    <div className={`absolute -right-4 -bottom-4 h-20 w-20 rounded-full opacity-[0.03] group-hover:opacity-[0.07] transition-opacity ${isToday ? 'bg-white' : 'bg-slate-900'}`} />
                  </CardContent>
                </Card>
              );
            })}
          </div>

          {/* Weekly Navigation & Quick Filters */}
          <div className="flex items-center justify-between bg-white p-4 rounded-3xl shadow-sm border border-slate-100">
            <div className="flex items-center gap-2">
              <Button variant="outline" className="rounded-xl border-slate-200 hover:bg-slate-50 font-black text-xs h-10 px-4" onClick={() => {
                const prevWeek = subDays(currentWeekStart, 7);
                setSearchParams({ ...searchParams, fromDate: format(prevWeek, "yyyy-MM-dd") });
              }}>
                <ChevronLeft className="h-4 w-4 mr-2" /> {t("examOfficer.schedulesPage.board.prevWeek")}
              </Button>
              <div className="px-6 py-2 bg-slate-50 rounded-xl border border-slate-100 font-bold text-slate-700 h-10 flex items-center gap-3">
                <Calendar className="h-4 w-4 text-orange-600" />
                <span>{format(currentWeekStart, "dd MMM")} — {format(addDays(currentWeekStart, 6), "dd MMM, yyyy")}</span>
              </div>
              <Button variant="outline" className="rounded-xl border-slate-200 hover:bg-slate-50 font-black text-xs h-10 px-4" onClick={() => {
                const nextWeek = addDays(currentWeekStart, 7);
                setSearchParams({ ...searchParams, fromDate: format(nextWeek, "yyyy-MM-dd") });
              }}>
                {t("examOfficer.schedulesPage.board.nextWeek")} <ChevronRight className="h-4 w-4 ml-2" />
              </Button>
            </div>

            <div className="flex gap-3">
              <select className="h-10 bg-slate-50 border border-slate-200 rounded-xl px-4 text-xs font-black uppercase outline-none focus:ring-2 focus:ring-orange-500/20" value={searchParams.campus} onChange={e => setSearchParams({ ...searchParams, campus: e.target.value })}>
                <option value="">{t("examOfficer.schedulesPage.allOptions.allCampuses")}</option>
                {CAMPUSES.map(c => <option key={c} value={c}>{c}</option>)}
              </select>
              <Button variant="ghost" className="h-10 text-[10px] font-black text-slate-400 hover:text-orange-600" onClick={clearFilters}>{t("examOfficer.schedulesPage.board.reset")}</Button>
            </div>
          </div>

          {/* The Scrollable Matrix Board */}
          <div className="relative bg-white border border-slate-200 rounded-[2.5rem] shadow-2xl overflow-hidden min-h-[700px]">
            <div className="overflow-x-auto scrollbar-thin scrollbar-thumb-slate-200 scrollbar-track-transparent">
              <div className="flex" style={{ width: 'max-content' }}>
                {/* Dynamic Time Sidebar */}
                <div className="sticky left-0 z-40 bg-white/95 backdrop-blur-md border-r border-slate-200 flex flex-col pt-[72px]">
                  {timeSlots.length > 0 ? timeSlots.map(time => (
                    <div key={time} className="h-[450px] w-28 px-2 flex flex-col justify-center border-b border-slate-100">
                      <div className="bg-slate-50 p-2 rounded-xl border border-slate-100 text-center">
                        <p className="text-[8px] font-black text-slate-400 uppercase tracking-widest mb-1">{t("examOfficer.schedulesPage.board.startTime")}</p>
                        <p className="font-black text-slate-900 border-b-2 border-orange-500 pb-0.5 text-base flex items-center justify-center gap-1.5">
                          <Clock className="h-3.5 w-3.5 text-orange-600" /> {time}
                        </p>
                      </div>
                    </div>
                  )) : (
                    <div className="w-28 h-full flex items-center justify-center p-4 text-center text-[9px] font-bold text-slate-300 italic">
                      N/A
                    </div>
                  )}
                </div>

                {/* Day Columns */}
                <div className="flex flex-1">
                  {gridDates.map(date => {
                    const isToday = isSameDay(parseISO(date), new Date());
                    return (
                      <div key={date} className={`w-[420px] border-r border-slate-100 flex flex-col bg-white ${isToday ? 'bg-orange-50/10' : ''}`}>
                        {/* Day Header */}
                        <div className={`sticky top-0 z-30 p-4 border-b border-slate-100 text-center h-[72px] flex flex-col justify-center relative ${isToday ? 'bg-orange-600 text-white shadow-xl' : 'bg-slate-900 text-white shadow-lg'}`}>
                          <p className="text-[10px] font-black uppercase tracking-[2px] opacity-70 mb-0.5">{tCommon("days." + format(parseISO(date), "EEEE").toLowerCase())}</p>
                          <h3 className="text-sm font-black tracking-tight">{format(parseISO(date), "dd MMM, yyyy")}</h3>
                          {isToday && <div className="absolute -bottom-1.5 left-1/2 -translate-x-1/2 bg-white text-orange-600 text-[8px] font-black px-3 py-0.5 rounded-full shadow-lg border border-orange-100 z-50">TODAY</div>}
                        </div>

                        {/* Time Slots Area */}
                        <div className="flex flex-col">
                          {timeSlots.map(time => {
                            const timeData = matrix[date]?.[time!] || {};
                            const campusesInSlot = CAMPUSES.filter(c => timeData[c] && timeData[c].length > 0);

                            return (
                              <div
                                key={time}
                                className="h-[450px] p-2 border-b border-slate-100 overflow-hidden hover:bg-slate-50/5 transition-colors flex flex-col"
                              >
                                <div
                                  className="h-full w-full p-2 overflow-y-auto scrollbar-thin scrollbar-thumb-slate-200 scrollbar-track-transparent flex flex-col gap-3"
                                  onDragOver={(e) => e.preventDefault()}
                                  onDrop={(e) => handleDrop(e, date, time!)}
                                >
                                  {campusesInSlot.length > 0 ? (
                                    campusesInSlot.map(campus => {
                                      const theme = campusThemes[campus] || campusThemes["HN"];
                                      const campusSessions = timeData[campus];
                                      return (
                                        <div
                                          key={campus}
                                          className={`${theme.bg} ${theme.border} border-2 rounded-2xl p-3 shadow-sm flex flex-col gap-3 transition-all duration-300 drop-shadow-sm`}
                                          onDragOver={(e) => {
                                            e.preventDefault();
                                            e.currentTarget.classList.add("ring-2", "ring-orange-500", "scale-[1.01]");
                                          }}
                                          onDragLeave={(e) => {
                                            e.currentTarget.classList.remove("ring-2", "ring-orange-500", "scale-[1.01]");
                                          }}
                                          onDrop={(e) => {
                                            e.currentTarget.classList.remove("ring-2", "ring-orange-500", "scale-[1.01]");
                                            handleDrop(e, date, time!, campus);
                                          }}
                                        >
                                          <div className="flex items-center justify-between border-b border-white/50 pb-2">
                                            <div className="flex items-center gap-2">
                                              <span className={`${theme.badge} text-[11px] text-white px-2.5 py-0.5 rounded-lg font-black uppercase tracking-wider shadow-sm`}>{campus}</span>
                                              <span className={`text-[11px] font-black ${theme.text} opacity-70 tracking-tight`}>{t("examOfficer.schedulesPage.campusLabel", { campus })}</span>
                                            </div>
                                            <div className="flex items-center gap-1.5 bg-white/80 px-3 py-1.5 rounded-full border border-white shadow-sm ring-4 ring-white/20">
                                              <span className={`text-sm font-black ${theme.text} leading-none`}>{campusSessions.length}</span>
                                              <span className={`text-[10px] font-black uppercase tracking-widest ${theme.text} opacity-60 leading-none`}>{t("examOfficer.schedulesPage.board.roomsSuffix")}</span>
                                            </div>
                                          </div>

                                          <div className="grid grid-cols-2 gap-2">
                                            {campusSessions.map((s: any) => (
                                              <div
                                                key={s.id}
                                                draggable
                                                onDragStart={(e) => handleDragStart(e, s.id)}
                                                onClick={() => router.push(`/${locale}${ROUTES.EXAMS_SCHEDULE_DETAIL(s.id)}`)}
                                                className={`group/card p-2.5 rounded-xl shadow-sm border transition-all cursor-pointer relative overflow-hidden flex flex-col gap-1.5 ${!s.proctorName ? 'bg-rose-50/30 border-rose-100 hover:border-rose-400' : 'bg-white border-slate-100 hover:border-orange-400'}`}
                                              >
                                                <div className="flex justify-between items-start">
                                                  <h4 className={`text-[15px] font-black uppercase truncate tracking-tight leading-none ${!s.proctorName ? 'text-rose-700' : 'text-slate-900 font-black'}`}>{s.subjectCode}</h4>
                                                  <div className="flex items-center gap-1 text-[10px] font-black text-white bg-gradient-to-r from-indigo-600 to-purple-600 px-2 py-0.5 rounded-lg leading-none shadow-sm shadow-indigo-100">
                                                    {s.examType}
                                                  </div>
                                                </div>

                                                <div className="flex items-center justify-between text-[11px] font-bold text-slate-500">
                                                  <div className="flex items-center gap-1.5">
                                                    <Clock className="h-3.5 w-3.5 text-slate-400" />
                                                    <span className="font-black text-slate-600">{getFormattedTimeRange(s.examOpenTime, s.examCloseTime)}</span>
                                                  </div>
                                                  <div className="flex items-center gap-1 bg-orange-100/50 text-orange-700 px-1.5 py-0.5 rounded-md">
                                                    <Users className="h-3 w-3" />
                                                    <span className="font-black tracking-tighter">{s.studentCount || 0}</span>
                                                  </div>
                                                </div>

                                                <div className="flex flex-col gap-1.5 mt-1">
                                                  <div className="flex items-center gap-2.5 text-xs font-black text-blue-700 bg-blue-50/50 px-2 py-1 rounded-lg border border-blue-100/50">
                                                    <MapPin className="h-3.5 w-3.5" />
                                                    <span className="truncate uppercase font-black">{s.roomNumber || "---"}</span>
                                                  </div>
                                                  <div className={`flex items-center gap-2.5 text-xs font-black px-2 py-1 rounded-lg border shadow-sm transition-colors ${s.proctorName ? 'text-slate-800 bg-slate-50 border-slate-200' : 'text-rose-700 bg-rose-50 border-rose-200 animate-pulse-subtle'}`}>
                                                    <Users className="h-3.5 w-3.5" />
                                                    <span className="truncate uppercase font-black">{s.proctorName || "CHƯA GÁN"}</span>
                                                  </div>
                                                </div>
                                              </div>
                                            ))}
                                          </div>
                                        </div>
                                      );
                                    })
                                  ) : (
                                    <div className="h-full min-h-[100px] flex flex-col items-center justify-center opacity-20 group/ready">
                                      <Plus className="h-8 w-8 text-slate-300 group-hover/ready:scale-125 transition-transform" />
                                      <span className="text-[10px] font-black text-slate-400 tracking-widest uppercase mt-2">{t("examOfficer.schedulesPage.board.ready")}</span>
                                    </div>
                                  )}
                                </div>
                              </div>
                            );
                          })}
                        </div>
                      </div>
                    );
                  })}
                </div>
              </div>
            </div>
          </div>
        </div>
      ) : (
        /* List View remains existing clean version */
        <Card className="border-none shadow-xl rounded-3xl overflow-hidden bg-white">
          <div className="overflow-x-auto">
            <table className="w-full text-sm text-left">
              <thead className="bg-[#1e293b] text-white text-[10px] font-black uppercase tracking-widest">
                <tr>
                  <th className="p-6">{t("examOfficer.table.campus")}</th>
                  <th className="p-6">{t("examOfficer.table.subject")}</th>
                  <th className="p-6">{t("examOfficer.table.date")}</th>
                  <th className="p-6 text-center">{t("examOfficer.table.time")}</th>
                  <th className="p-6">{t("examOfficer.table.type")}</th>
                  <th className="p-6">{t("examOfficer.table.room")}</th>
                  <th className="p-6">{t("examOfficer.schedulesPage.board.studentSuffix")}</th>
                  <th className="p-6">{t("examOfficer.table.status")}</th>
                  <th className="p-6 text-right pr-10">{tCommon("actions")}</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {isLoading ? (
                  <tr><td colSpan={10} className="p-24 text-center text-slate-400 font-bold italic">{tCommon("loading")}</td></tr>
                ) : schedules.length === 0 ? (
                  <tr><td colSpan={10} className="p-24 text-center text-slate-400 font-bold italic">{tCommon("noResults")}</td></tr>
                ) : schedules.map(s => (
                  <tr key={s.id} className="hover:bg-slate-50 transition-colors cursor-pointer group" onClick={() => router.push(`/${locale}${ROUTES.EXAMS_SCHEDULE_DETAIL(s.id)}`)}>
                    <td className="p-5 px-6"><span className={`${campusThemes[s.campus || "HN"].badge} text-white px-3 py-1 rounded-xl text-[10px] font-black shadow-sm`}>{s.campus}</span></td>
                    <td className="p-5 font-black text-slate-800 group-hover:text-orange-600 transition-colors text-base uppercase">{s.subjectCode}</td>
                    <td className="p-5 font-bold text-slate-500">{s.examOpenTime ? format(parseLocalDate(s.examOpenTime)!, "dd/MM/yyyy") : "-"}</td>
                    <td className="p-5 text-center"><div className="flex items-center justify-center gap-1.5 font-black text-slate-700 italic"><Clock className="h-4 w-4 text-orange-500" />{s.examOpenTime ? format(parseLocalDate(s.examOpenTime)!, "HH:mm") : "-"}</div></td>
                    <td className="p-5 text-[10px] font-bold text-slate-400 uppercase tracking-widest">{s.examType}</td>
                    <td className="p-5 font-black text-slate-700">{s.roomNumber}</td>
                    <td className="p-5 font-black text-orange-600">{s.studentCount || 0}</td>
                    <td className="p-5"><span className={`text-[10px] font-black px-4 py-1.5 rounded-full border shadow-sm ${s.status === 'Draft' ? 'bg-orange-50 text-orange-600 border-orange-100' : 'bg-green-50 text-green-600 border-green-100'}`}>{tCommon(`statuses.${s.status}`)}</span></td>
                    <td className="p-5 text-right pr-10"><Button variant="ghost" size="sm" className="h-10 w-10 p-0 rounded-2xl hover:bg-white hover:shadow-lg"><MoreVertical className="h-5 w-5 text-slate-300" /></Button></td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <div className="p-6 border-t border-slate-100 bg-slate-50/30 flex items-center justify-between">
            <div className="text-xs font-black text-slate-400 tracking-widest italic uppercase">{tCommon("showing")} {schedules.length} {t("examOfficer.schedules")} / {tCommon("page")} {page}</div>
            <div className="flex gap-3">
              <Button size="sm" variant="outline" className="h-10 px-6 rounded-2xl font-black bg-white shadow-sm border-slate-200" onClick={() => setPage(p => p - 1)} disabled={page === 1}>{tCommon("previous")}</Button>
              <Button size="sm" variant="outline" className="h-10 px-6 rounded-2xl font-black bg-white shadow-sm border-slate-200" onClick={() => setPage(p => p + 1)} disabled={page === totalPages}>{tCommon("next")}</Button>
            </div>
          </div>
        </Card>
      )}

      {/* Legend Footer */}
      <div className="flex flex-wrap gap-8 items-center justify-center bg-white p-6 rounded-[2.5rem] border border-slate-100 shadow-xl mt-4">
        {Object.entries(campusThemes).map(([campus, theme]) => (
          <div key={campus} className="flex items-center gap-3">
            <div className={`w-4 h-4 rounded-xl ${theme.badge} shadow-lg ${theme.shadow}`} />
            <span className="text-xs font-black text-slate-500 uppercase tracking-widest">{t("examOfficer.schedulesPage.campusLabel", { campus })}</span>
            <div className="h-1.5 w-12 bg-slate-100 rounded-full ml-1" />
          </div>
        ))}
      </div>

      <ImportScheduleDialog isOpen={showScheduleDialog} onClose={() => setShowScheduleDialog(false)} />
      <ImportProctorDialog isOpen={showProctorDialog} onClose={() => setShowProctorDialog(false)} />
      <ImportExamCodeDialog isOpen={showExamCodeDialog} onClose={() => setShowExamCodeDialog(false)} />
      <AutoGenerateScheduleDialog isOpen={showAutoGenerateDialog} onClose={() => setShowAutoGenerateDialog(false)} />
    </div>
  );
}
